---
title: "Practical Statistics"
output: html_notebook
---

# 1. EXPLORATORY DATA ANALYSIS

```{r}

library(dplyr)
library(tidyr)
library(ggplot2)
library(vioplot)
library(ascii)
library(corrplot)
library(descr)

```

## 1.1. Estimates of Location

```{r}

#Mean, trimmed mean and median
state <- read.csv(file = "data/state.csv")

mean(state$Population)

mean(state[["Population"]], trim = 0.1)

median(state[["Population"]]) # more robust metrics of location

#Weighted mean and weighted median
weighted.mean(state$Murder.Rate, w = state$Population)

library("matrixStats")
weightedMedian(state$Murder.Rate, w = state$Population) # more robust metrics of location

```

## 1.2. Estimates of Variability

```{r}

#Standard deviation, Interquartile range (IRQ), median absolution deviation (MAD)

sd(state$Population)

IQR(state[["Population"]])

mad(state[["Population"]]) # more robust metrics of variability MAD is equal to median(|xi – x|)

#Percentiles
quantile(state$Murder.Rate, p = c(0.05, 0.35, 0.50, 0.75, 0.95))

#Boxplots
boxplot(state[["Population"]] / 1000000, ylab = "Populations (millions)")

#Frequency table
breaks <- seq(from = min(state[["Population"]]),
              to = max(state[["Population"]]),
              length = 11)
pop_freq <- cut(state[["Population"]],
                breaks = breaks,
                right = TRUE,
                include.lowest = TRUE)
state['PopFreq'] <- pop_freq
table(pop_freq)

## Code for FreqTable
state_abb <- state %>%
  arrange(Population) %>%
  group_by(PopFreq) %>%
  summarize(state = paste(Abbreviation, collapse = ","),
            .drop = FALSE) %>%
  complete(PopFreq, fill = list(state = '')) %>%
  select(state)

state_abb <- unlist(state_abb)

lower_br <- formatC(breaks[1:10],
                    format = "d",
                    digits = 0,
                    big.mark = ",")
upper_br <- formatC(
  c(breaks[2:10] - 1, breaks[11]),
  format = "d",
  digits = 0,
  big.mark = ","
)

pop_table <- data.frame(
  "BinNumber" = 1:10,
  "BinRange" = paste(lower_br, upper_br, sep = "-"),
  "Count" = as.numeric(table(pop_freq)),
  "States" = state_abb
)

ascii(
  pop_table,
  include.rownames = FALSE,
  digits = c(0, 0, 0, 0),
  align = c("l", "r", "r", "l"),
  caption = "A frequency table of population by state."
)

View(pop_table)

#Histogram of frequecies
hist(state[["Population"]], breaks = breaks)

#Density estimates
hist(state[["Murder.Rate"]], freq = FALSE)
lines(density(state[["Murder.Rate"]]), lwd = 3, col = "blue")

```

## 1.3. Exploring Binary and Category Data

```{r}

#Frequency of proportion of each category value
dfw <- read.csv(file = "data/dfw_airline.csv")

barplot(as.matrix(dfw) / 6, cex.axis = 0.5)

#Mode
library(modeest)
mode = mlv(state$Murder.Rate, method = "mfv")
print(mode)

barplot(as.matrix(dfw), col = c(4, rep("gray", 4)))
legend("topright", "Mode", fill = 4)

#Expected Value: probability by value, it's a kind of median weight

ev = (0.05) * (300) + (0.15) * 50 + (0.80) * 120
print(ev)

```

## 1.4. Correlation

```{r}

#Matrix correlation
sp500_px <- read.csv(file = 'data/sp500_data.csv', row.names = 1)
sp500_sym <- read.csv(file = 'data/sp500_sectors.csv', stringsAsFactors = FALSE)

telecom <- sp500_px[, sp500_sym[sp500_sym$sector == "telecommunications_services", 'symbol']]
telecom <- telecom[row.names(telecom) > "2012-07-01", ]
telecom_cor <- cor(telecom)
ascii(
  telecom_cor,
  digits = c(3, 3, 3, 3, 3),
  align = c("l", "r", "r", "r", "r", "r"),
  caption = "Correlation between telecommunication stock returns.",
  include.rownames = TRUE,
  include.colnames = TRUE
)

#Gráfico
etfs <- sp500_px[row.names(sp500_px) > '2012-07-01', sp500_sym[sp500_sym$sector == 'etf', 'symbol']]
library(corrplot)
corrplot(cor(etfs), method = 'ellipse')


### Scatterplots

# plot(telecom$T, telecom$VZ, xlab='T', ylab='VZ', cex=.8)
plot(telecom$T, telecom$VZ, xlab = 'ATT (T)', ylab = 'Verizon (VZ)')
abline(h = 0, v = 0, col = 'grey')
dim(telecom)

```

## 1.5. Exploring two or more variables

```{r}

# Load the kc_tax dataset and filter based on a variety of criteria
kc_tax <- read.csv(file = 'data/kc_tax.csv.gz')

kc_tax0 <- subset(kc_tax, TaxAssessedValue < 750000 & 
                    SqFtTotLiving > 100 &
                    SqFtTotLiving < 3500)
nrow(kc_tax0)

### Hexagonal binning and Contours
#### Plotting numeric versus numeric data

# If the number of data points gets large, scatter plots will no longer be meaningful. Here methods that visualize densities are more useful. The `stat_hexbin` method for is one powerful approach.

graph <- ggplot(kc_tax0, (aes(x=SqFtTotLiving, y=TaxAssessedValue))) + 
  stat_binhex(color='white') + 
  theme_bw() + 
  scale_fill_gradient(low='white', high='blue') +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  labs(x='Finished Square Feet', y='Tax-Assessed Value')
graph

# Visualize as a two-dimensional extension of the density plot.

graph <- ggplot(kc_tax0, aes(SqFtTotLiving, TaxAssessedValue)) +
  theme_bw() + 
  geom_point(color='blue', alpha=0.1) + 
  geom_density2d(color='white') + 
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  labs(x='Finished Square Feet', y='Tax-Assessed Value')
graph


### Two Categorical Variables
# Load the `lc_loans` dataset

lc_loans <- read.csv(file = 'data/lc_loans.csv')

x_tab <- CrossTable(lc_loans$grade, lc_loans$status, 
                    prop.c=FALSE, prop.chisq=FALSE, prop.t=FALSE)
print(x_tab)

### Categorical and Numeric Data
# Boxplots of a column can be grouped by a different column.

airline_stats <- read.csv(file = 'data/airline_stats.csv', stringsAsFactors = FALSE)


boxplot(pct_carrier_delay ~ airline, data=airline_stats, ylim=c(0, 50), 
        cex.axis=.6, ylab='Daily % of Delayed Flights')

# Variation of boxplots called _violinplot_.

graph <- ggplot(data=airline_stats, aes(airline, pct_carrier_delay)) + 
  geom_violin(draw_quantiles = c(.25,.5,.75), linetype=2) +
  geom_violin(fill=NA, size=1.1) +
  coord_cartesian(ylim=c(0, 50)) +
  labs(x='', y='Daily % of Delayed Flights') +
  theme_bw()
graph

### Visualizing Multiple Variables

graph <- ggplot(subset(kc_tax0, ZipCode %in% c(98188, 98105, 98108, 98126)),
                aes(x=SqFtTotLiving, y=TaxAssessedValue)) + 
  stat_binhex(colour='white') + 
  theme_bw() + 
  scale_fill_gradient(low='gray95', high='black') +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  labs(x='Finished Square Feet', y='Tax-Assessed Value') +
  facet_wrap('ZipCode')
graph


```

